backend:
  name: test-repo

media_folder: "images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "pages/index.json"
        fields:
          - {label: Header, name: header, widget: string}
